CloudAppEvents
| where Timestamp between (datetime(2026-07-21T20:02:22) .. datetime(2026-07-21T20:21:42))
| where Application contains "OneDrive" or Application contains "Sharepoint"
| extend RawUPN = tostring(RawEventData.UserId)
| where RawUPN =~ "marcie.carpenter@omniapartners.com"
| extend InWindow = Timestamp between (datetime(2026-07-21T20:07:22) .. datetime(2026-07-21T20:16:42))
| extend SecondsFromStart = datetime_diff('second', Timestamp, datetime(2026-07-21T20:07:22))
| extend SecondsFromEnd   = datetime_diff('second', Timestamp, datetime(2026-07-21T20:16:42))
| project Timestamp, RawUPN, ActionType, ObjectName, InWindow, SecondsFromStart, SecondsFromEnd
| order by Timestamp asc
