CloudAppEvents
| where Timestamp between (datetime(2026-07-20T17:38:53) .. datetime(2026-07-20T18:03:06))
| where Application contains "OneDrive" or Application contains "Sharepoint"
| extend RawUPN = tostring(RawEventData.UserId)
| where RawUPN =~ "marcie.carpenter@omniapartners.com"
| extend InWindow = Timestamp between (datetime(2026-07-20T17:43:53) .. datetime(2026-07-20T17:58:06))
| extend SecondsFromStart = datetime_diff('second', Timestamp, datetime(2026-07-20T17:43:53))
| extend SecondsFromEnd   = datetime_diff('second', Timestamp, datetime(2026-07-20T17:58:06))
| project Timestamp, RawUPN, ActionType, ObjectName, InWindow, SecondsFromStart, SecondsFromEnd
| order by Timestamp asc
