CloudAppEvents
| where Timestamp between (datetime(2026-07-16T21:00:48) .. datetime(2026-07-16T21:31:14))
| where Application contains "OneDrive" or Application contains "Sharepoint"
| extend RawUPN = tostring(RawEventData.UserId)
| where RawUPN =~ "gabriella.triano@omniapartners.com"
| extend InWindow = Timestamp between (datetime(2026-07-16T21:05:48) .. datetime(2026-07-16T21:26:14))
| extend SecondsFromStart = datetime_diff('second', Timestamp, datetime(2026-07-16T21:05:48))
| extend SecondsFromEnd   = datetime_diff('second', Timestamp, datetime(2026-07-16T21:26:14))
| project Timestamp, RawUPN, ActionType, ObjectName, InWindow, SecondsFromStart, SecondsFromEnd
| order by Timestamp asc
