DeviceNetworkEvents
| where DeviceName contains "1272" or DeviceName contains "1294"
| where RemoteUrl has_any ("salesforce.com", "force.com", "dayforce.com", "dayforcehcm.com", "ceridian.com")
| where (DeviceName contains "1294" and Timestamp between (datetime(2026-07-16T21:00:48) .. datetime(2026-07-16T21:31:14)))
    or (DeviceName contains "1272" and (
        Timestamp between (datetime(2026-07-20T17:38:53) .. datetime(2026-07-20T18:03:06))
        or Timestamp between (datetime(2026-07-21T20:02:22) .. datetime(2026-07-21T20:21:42))
    ))
| project Timestamp, DeviceName, RemoteIP, RemoteUrl, RemotePort, InitiatingProcessFileName, InitiatingProcessAccountName
| order by Timestamp asc
