let TIDomains =
    ThreatIntelIndicators
    | where IsDeleted == false
    | where ValidUntil > now()
    | where ObservableKey == "domain-name:value"
    | project TI_Domain = ObservableValue, Confidence, Description;
EmailEvents
| where Timestamp > ago(24h)
| extend SenderDomain = tostring(split(SenderFromAddress, "@")[1])
| join kind=inner TIDomains on $left.SenderDomain == $right.TI_Domain
| project Timestamp, SenderFromAddress, SenderDomain,
          RecipientEmailAddress, Subject, TI_Domain, Confidence
| order by Timestamp desc
