CloudAppEvents
| where Timestamp between (datetime(2026-07-20T17:36:32) .. datetime(2026-07-20T17:48:27))
| where Application contains "OneDrive" or Application contains "Sharepoint"
| extend RawUPN = tostring(RawEventData.UserId)
| where RawUPN =~ "marcie.carpenter@omniapartners.com"
| extend InWindow = Timestamp between (datetime(2026-07-20T17:41:32) .. datetime(2026-07-20T17:43:27))
| extend SecondsFromStart = datetime_diff('second', Timestamp, datetime(2026-07-20T17:41:32))
| extend SecondsFromEnd   = datetime_diff('second', Timestamp, datetime(2026-07-20T17:43:27))
| project Timestamp, RawUPN, ActionType, ObjectName, InWindow, SecondsFromStart, SecondsFromEnd
| order by Timestamp asc
